I need help

I keep getting this error 

C:\Users\DJblaze\Documents\Crypto\login\PinkKush\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3.1\plugins\python-ce\helpers\pydev\pydevconsole.py" --mode=client --port=53753
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\DJblaze\\Documents\\Crypto\\login', 'C:/Users/DJblaze/Documents/Crypto/login'])
PyDev console: starting.
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
runfile('C:/Users/DJblaze/Documents/Crypto/login/Login/app.py', wdir='C:/Users/DJblaze/Documents/Crypto/login/Login')
C:\Users\DJblaze\Documents\Crypto\login\PinkKush\lib\site-packages\flask_sqlalchemy\__init__.py:851: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///database.db".
  warnings.warn(
 * Restarting with stat
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
C:\Users\DJblaze\Documents\Crypto\login\PinkKush\lib\site-packages\flask_sqlalchemy\__init__.py:851: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///database.db".
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 110-950-866
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


im unsure how to fix this.E A STEP BY STEP ON WHAT THE HECK IS WRONG AND WHAT IVE NOT DONE!!!!!!!! CANT FIND ANY HELP!!!!
